<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `countries` (`id`, `created_at`, `updated_at`, `title`, `title_en`) VALUES
			(1, NULL, NULL, NULL, 'Afghanistan'),
			(2, NULL, NULL, NULL, 'Albania'),
			(3, NULL, NULL, NULL, 'Algeria'),
			(4, NULL, NULL, NULL, 'Andorra'),
			(5, NULL, NULL, NULL, 'Angola'),
			(6, NULL, NULL, NULL, 'Antigua and Barbuda'),
			(7, NULL, NULL, NULL, 'Argentina'),
			(8, NULL, NULL, NULL, 'Armenia'),
			(9, NULL, NULL, NULL, 'Australia'),
			(10, NULL, NULL, NULL, 'Austria'),
			(11, NULL, NULL, NULL, 'Azerbaijan'),
			(12, NULL, NULL, NULL, 'Bahamas'),
			(13, NULL, NULL, NULL, 'Bahrain'),
			(14, NULL, NULL, NULL, 'Bangladesh'),
			(15, NULL, NULL, NULL, 'Barbados'),
			(16, NULL, NULL, NULL, 'Belarus'),
			(17, NULL, NULL, NULL, 'Belgium'),
			(18, NULL, NULL, NULL, 'Belize'),
			(19, NULL, NULL, NULL, 'Benin'),
			(20, NULL, NULL, NULL, 'Bhutan'),
			(21, NULL, NULL, NULL, 'Bolivia (Plurinational State of)'),
			(22, NULL, NULL, NULL, 'Bosnia and Herzegovina'),
			(23, NULL, NULL, NULL, 'Botswana'),
			(24, NULL, NULL, NULL, 'Brazil'),
			(25, NULL, NULL, NULL, 'Brunei Darussalam'),
			(26, NULL, NULL, NULL, 'Bulgaria'),
			(27, NULL, NULL, NULL, 'Burkina Faso'),
			(28, NULL, NULL, NULL, 'Burundi'),
			(29, NULL, NULL, NULL, 'Cabo Verde'),
			(30, NULL, NULL, NULL, 'Cambodia'),
			(31, NULL, NULL, NULL, 'Cameroon'),
			(32, NULL, NULL, NULL, 'Canada'),
			(33, NULL, NULL, NULL, 'Central African Republic'),
			(34, NULL, NULL, NULL, 'Chad'),
			(35, NULL, NULL, NULL, 'Chile'),
			(36, NULL, NULL, NULL, 'China'),
			(37, NULL, NULL, NULL, 'Colombia'),
			(38, NULL, NULL, NULL, 'Comoros'),
			(39, NULL, NULL, NULL, 'Congo'),
			(40, NULL, NULL, NULL, 'Costa Rica'),
			(41, NULL, NULL, NULL, 'Côte D\'Ivoire'),
			(42, NULL, NULL, NULL, 'Croatia'),
			(43, NULL, NULL, NULL, 'Cuba'),
			(44, NULL, NULL, NULL, 'Cyprus'),
			(45, NULL, NULL, NULL, 'Czech Republic'),
			(46, NULL, NULL, NULL, 'Democratic People\'s Republic of Korea'),
			(47, NULL, NULL, NULL, 'Democratic Republic of the Congo'),
			(48, NULL, NULL, NULL, 'Denmark'),
			(49, NULL, NULL, NULL, 'Djibouti'),
			(50, NULL, NULL, NULL, 'Dominica'),
			(51, NULL, NULL, NULL, 'Dominican Republic'),
			(52, NULL, NULL, NULL, 'Ecuador'),
			(53, NULL, NULL, NULL, 'Egypt'),
			(54, NULL, NULL, NULL, 'El Salvador'),
			(55, NULL, NULL, NULL, 'Equatorial Guinea'),
			(56, NULL, NULL, NULL, 'Eritrea'),
			(57, NULL, NULL, NULL, 'Estonia'),
			(58, NULL, NULL, NULL, 'Ethiopia'),
			(59, NULL, NULL, NULL, 'Fiji'),
			(60, NULL, NULL, NULL, 'Finland'),
			(61, NULL, NULL, NULL, 'France'),
			(62, NULL, NULL, NULL, 'Gabon'),
			(63, NULL, NULL, NULL, 'Gambia (Republic of The)'),
			(64, NULL, NULL, NULL, 'Georgia'),
			(65, NULL, NULL, NULL, 'Germany'),
			(66, NULL, NULL, NULL, 'Ghana'),
			(67, NULL, NULL, NULL, 'Greece'),
			(68, NULL, NULL, NULL, 'Grenada'),
			(69, NULL, NULL, NULL, 'Guatemala'),
			(70, NULL, NULL, NULL, 'Guinea'),
			(71, NULL, NULL, NULL, 'Guinea Bissau'),
			(72, NULL, NULL, NULL, 'Guyana'),
			(73, NULL, NULL, NULL, 'Haiti'),
			(74, NULL, NULL, NULL, 'Honduras'),
			(75, NULL, NULL, NULL, 'Hungary'),
			(76, NULL, NULL, NULL, 'Iceland'),
			(77, NULL, NULL, NULL, 'India'),
			(78, NULL, NULL, NULL, 'Indonesia'),
			(79, NULL, NULL, NULL, 'Iran (Islamic Republic of)'),
			(80, NULL, NULL, NULL, 'Iraq'),
			(81, NULL, NULL, NULL, 'Ireland'),
			(82, NULL, NULL, NULL, 'Israel'),
			(83, NULL, NULL, NULL, 'Italy'),
			(84, NULL, NULL, NULL, 'Jamaica'),
			(85, NULL, NULL, NULL, 'Japan'),
			(86, NULL, NULL, NULL, 'Jordan'),
			(87, NULL, NULL, NULL, 'Kazakhstan'),
			(88, NULL, NULL, NULL, 'Kenya'),
			(89, NULL, NULL, NULL, 'Kiribati'),
			(90, NULL, NULL, NULL, 'Kuwait'),
			(91, NULL, NULL, NULL, 'Kyrgyzstan'),
			(92, NULL, NULL, NULL, 'Lao People’s Democratic Republic'),
			(93, NULL, NULL, NULL, 'Latvia'),
			(94, NULL, NULL, NULL, 'Lebanon'),
			(95, NULL, NULL, NULL, 'Lesotho'),
			(96, NULL, NULL, NULL, 'Liberia'),
			(97, NULL, NULL, NULL, 'Libya'),
			(98, NULL, NULL, NULL, 'Liechtenstein'),
			(99, NULL, NULL, NULL, 'Lithuania'),
			(100, NULL, NULL, NULL, 'Luxembourg'),
			(101, NULL, NULL, NULL, 'Madagascar'),
			(102, NULL, NULL, NULL, 'Malawi'),
			(103, NULL, NULL, NULL, 'Malaysia'),
			(104, NULL, NULL, NULL, 'Maldives'),
			(105, NULL, NULL, NULL, 'Mali'),
			(106, NULL, NULL, NULL, 'Malta'),
			(107, NULL, NULL, NULL, 'Marshall Islands'),
			(108, NULL, NULL, NULL, 'Mauritania'),
			(109, NULL, NULL, NULL, 'Mauritius'),
			(110, NULL, NULL, NULL, 'Mexico'),
			(111, NULL, NULL, NULL, 'Micronesia (Federated States of)'),
			(112, NULL, NULL, NULL, 'Monaco'),
			(113, NULL, NULL, NULL, 'Mongolia'),
			(114, NULL, NULL, NULL, 'Montenegro'),
			(115, NULL, NULL, NULL, 'Morocco'),
			(116, NULL, NULL, NULL, 'Mozambique'),
			(117, NULL, NULL, NULL, 'Myanmar'),
			(118, NULL, NULL, NULL, 'Namibia'),
			(119, NULL, NULL, NULL, 'Nauru'),
			(120, NULL, NULL, NULL, 'Nepal'),
			(121, NULL, NULL, NULL, 'Netherlands'),
			(122, NULL, NULL, NULL, 'New Zealand'),
			(123, NULL, NULL, NULL, 'Nicaragua'),
			(124, NULL, NULL, NULL, 'Niger'),
			(125, NULL, NULL, NULL, 'Nigeria'),
			(126, NULL, NULL, NULL, 'Norway'),
			(127, NULL, NULL, NULL, 'Oman'),
			(128, NULL, NULL, NULL, 'Pakistan'),
			(129, NULL, NULL, NULL, 'Palau'),
			(130, NULL, NULL, NULL, 'Panama'),
			(131, NULL, NULL, NULL, 'Papua New Guinea'),
			(132, NULL, NULL, NULL, 'Paraguay'),
			(133, NULL, NULL, NULL, 'Peru'),
			(134, NULL, NULL, NULL, 'Philippines'),
			(135, NULL, NULL, NULL, 'Poland'),
			(136, NULL, NULL, NULL, 'Portugal'),
			(137, NULL, NULL, NULL, 'Qatar'),
			(138, NULL, NULL, NULL, 'Republic of Korea'),
			(139, NULL, NULL, NULL, 'Republic of Moldova'),
			(140, NULL, NULL, NULL, 'Romania'),
			(141, NULL, NULL, NULL, 'Russian Federation'),
			(142, NULL, NULL, NULL, 'Rwanda'),
			(143, NULL, NULL, NULL, 'Saint Kitts and Nevis'),
			(144, NULL, NULL, NULL, 'Saint Lucia'),
			(145, NULL, NULL, NULL, 'Saint Vincent and the Grenadines'),
			(146, NULL, NULL, NULL, 'Samoa'),
			(147, NULL, NULL, NULL, 'San Marino'),
			(148, NULL, NULL, NULL, 'Sao Tome and Principe'),
			(149, NULL, NULL, NULL, 'Saudi Arabia'),
			(150, NULL, NULL, NULL, 'Senegal'),
			(151, NULL, NULL, NULL, 'Serbia'),
			(152, NULL, NULL, NULL, 'Seychelles'),
			(153, NULL, NULL, NULL, 'Sierra Leone'),
			(154, NULL, NULL, NULL, 'Singapore'),
			(155, NULL, NULL, NULL, 'Slovakia'),
			(156, NULL, NULL, NULL, 'Slovenia'),
			(157, NULL, NULL, NULL, 'Solomon Islands'),
			(158, NULL, NULL, NULL, 'Somalia'),
			(159, NULL, NULL, NULL, 'South Africa'),
			(160, NULL, NULL, NULL, 'South Sudan'),
			(161, NULL, NULL, NULL, 'Spain'),
			(162, NULL, NULL, NULL, 'Sri Lanka'),
			(163, NULL, NULL, NULL, 'Sudan'),
			(164, NULL, NULL, NULL, 'Suriname'),
			(165, NULL, NULL, NULL, 'Swaziland'),
			(166, NULL, NULL, NULL, 'Sweden'),
			(167, NULL, NULL, NULL, 'Switzerland'),
			(168, NULL, NULL, NULL, 'Syrian Arab Republic'),
			(169, NULL, NULL, NULL, 'Tajikistan'),
			(170, NULL, NULL, NULL, 'Thailand'),
			(171, NULL, NULL, NULL, 'The former Yugoslav Republic of Macedonia'),
			(172, NULL, NULL, NULL, 'Timor-Leste'),
			(173, NULL, NULL, NULL, 'Togo'),
			(174, NULL, NULL, NULL, 'Tonga'),
			(175, NULL, NULL, NULL, 'Trinidad and Tobago'),
			(176, NULL, NULL, NULL, 'Tunisia'),
			(177, NULL, NULL, NULL, 'Turkey'),
			(178, NULL, NULL, NULL, 'Turkmenistan'),
			(179, NULL, NULL, NULL, 'Tuvalu'),
			(180, NULL, NULL, NULL, 'Uganda'),
			(181, NULL, NULL, NULL, 'Ukraine'),
			(182, NULL, NULL, NULL, 'United Arab Emirates'),
			(183, NULL, NULL, NULL, 'United Kingdom of Great Britain and Northern Ireland'),
			(184, NULL, NULL, NULL, 'United Republic of Tanzania'),
			(185, NULL, NULL, NULL, 'United States of America'),
			(186, NULL, NULL, NULL, 'Uruguay'),
			(187, NULL, NULL, NULL, 'Uzbekistan'),
			(188, NULL, NULL, NULL, 'Vanuatu'),
			(189, NULL, NULL, NULL, 'Venezuela, Bolivarian Republic of'),
			(190, NULL, NULL, NULL, 'Viet Nam'),
			(191, NULL, NULL, NULL, 'Yemen'),
			(192, NULL, NULL, NULL, 'Zambia'),
			(193, NULL, NULL, NULL, 'Zimbabwe');");
    }
}
